In [1]:
from transformers import GPT2LMHeadModel

In [2]:
model_hf = GPT2LMHeadModel.from_pretrained("gpt2") # 124 M
sd_gpt_2 = model_hf.state_dict()

for k, v in sd_gpt_2.items():
    print(f"layer: {k}, shape: {v.shape}")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

layer: transformer.wte.weight, shape: torch.Size([50257, 768])
layer: transformer.wpe.weight, shape: torch.Size([1024, 768])
layer: transformer.h.0.ln_1.weight, shape: torch.Size([768])
layer: transformer.h.0.ln_1.bias, shape: torch.Size([768])
layer: transformer.h.0.attn.c_attn.weight, shape: torch.Size([768, 2304])
layer: transformer.h.0.attn.c_attn.bias, shape: torch.Size([2304])
layer: transformer.h.0.attn.c_proj.weight, shape: torch.Size([768, 768])
layer: transformer.h.0.attn.c_proj.bias, shape: torch.Size([768])
layer: transformer.h.0.ln_2.weight, shape: torch.Size([768])
layer: transformer.h.0.ln_2.bias, shape: torch.Size([768])
layer: transformer.h.0.mlp.c_fc.weight, shape: torch.Size([768, 3072])
layer: transformer.h.0.mlp.c_fc.bias, shape: torch.Size([3072])
layer: transformer.h.0.mlp.c_proj.weight, shape: torch.Size([3072, 768])
layer: transformer.h.0.mlp.c_proj.bias, shape: torch.Size([768])
layer: transformer.h.1.ln_1.weight, shape: torch.Size([768])
layer: transformer.h.

In [6]:
from transformers import pipeline, set_seed 
generator = pipeline('text-generation', model='gpt2')
set_seed(42)

generator("Hello I am a language model", max_length=10, num_return_sequences=5)

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] Both `max_new_tokens` (=256) and `max_length`(=10) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': 'Hello I am a language modeler, I am not a linguist or a spacecraft engineer. I am a teacher. I am a translator. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I are a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a teacher. I am a'},
 {'generated_text': 'Hello I am a language modeler and not an engineer. I take the role of programmer as if I are a prog

In [4]:
import torch
import torch.nn.functional as F
import math 

x = torch.randn(5, 5)
mask = torch.triu(torch.ones(5,5), diagonal=1).type(torch.bool)

x.masked_fill(mask, float('-inf'))


tensor([[ 1.9269,    -inf,    -inf,    -inf,    -inf],
        [-1.2345, -0.0431,    -inf,    -inf,    -inf],
        [-0.4934,  0.2415, -1.1109,    -inf,    -inf],
        [-0.2168, -1.3847, -0.3957,  0.8034,    -inf],
        [-0.5920, -0.0631, -0.8286,  0.3309, -1.5576]])

In [5]:
def test_scaled_attention():
    torch.manual_seed(42)

    B = 2
    H = 2
    T = 4
    Dh = 4

    Q = torch.randn(B, H, T, Dh)
    K = torch.randn(B, H, T, Dh)
    V = torch.randn(B, H, T, Dh)

    # -------------------------
    # Your implementation
    # -------------------------

    scores = Q @ K.transpose(-1, -2)

    scores = scores / math.sqrt(Dh)

    mask = torch.triu(
        torch.ones(T, T, dtype=torch.bool),
        diagonal=1
    )

    scores = scores.masked_fill(mask, float("-inf"))

    attn_weights = F.softmax(scores, dim=-1)

    my_output = attn_weights @ V

    # -------------------------
    # PyTorch reference
    # -------------------------

    reference_output = F.scaled_dot_product_attention(
        Q,
        K,
        V,
        dropout_p=0.0,
        is_causal=True,
    )

    assert torch.allclose(
        my_output,
        reference_output,
        atol=1e-5,
        rtol=1e-5,
    )

test_scaled_attention() 

In [42]:
x = torch.randn(100)
x = F.softmax(x, dim=-1)
print(x)
topk_vals, topk_indices = torch.topk(x, 3, dim=-1)
print(topk_vals)
print(topk_indices)

ix = torch.multinomial(topk_vals, 1)
print(ix)

torch.gather(topk_indices, -1, ix)

tensor([0.0123, 0.0047, 0.0139, 0.0044, 0.0013, 0.0054, 0.0012, 0.0087, 0.0032,
        0.0017, 0.0069, 0.0039, 0.0056, 0.0164, 0.0029, 0.0019, 0.0036, 0.0208,
        0.0030, 0.0218, 0.0050, 0.0267, 0.0284, 0.0008, 0.0106, 0.0033, 0.0930,
        0.0132, 0.0137, 0.0018, 0.0030, 0.0118, 0.0130, 0.0044, 0.0022, 0.0151,
        0.0057, 0.0070, 0.0122, 0.0205, 0.0161, 0.0054, 0.0027, 0.0029, 0.0026,
        0.0078, 0.0018, 0.0261, 0.0054, 0.0158, 0.0130, 0.0112, 0.0103, 0.0046,
        0.0056, 0.0010, 0.0264, 0.0263, 0.0019, 0.0028, 0.0243, 0.0068, 0.0071,
        0.0092, 0.0032, 0.0046, 0.0171, 0.0092, 0.0141, 0.0034, 0.0013, 0.0109,
        0.0009, 0.0227, 0.0105, 0.0052, 0.0039, 0.0524, 0.0026, 0.0036, 0.0073,
        0.0135, 0.0040, 0.0423, 0.0052, 0.0163, 0.0021, 0.0005, 0.0093, 0.0115,
        0.0074, 0.0051, 0.0019, 0.0039, 0.0025, 0.0097, 0.0007, 0.0021, 0.0095,
        0.0075])
tensor([0.0930, 0.0524, 0.0423])
tensor([26, 77, 83])
tensor([0])


tensor([26])